#!/bin/bash

DF="/etc/openvpn"

echo ""
echo "Tell me a name for the client."
echo "The name must consist of alphanumeric characters. It may also include an underscore or a dash."

until [[ $CLIENT =~ ^[a-zA-Z0-9_-]+$ ]]; do
    read -rp "Client name: " -e CLIENT
done

echo ""
echo "Do you want to protect the configuration file with a password?"
echo "(e.g. encrypt the private key with a password)"
echo "   1) Add a passwordless client"
echo "   2) Use a password for the client"

until [[ $PASS =~ ^[1-2]$ ]]; do
    read -rp "Select an option [1-2]: " -e -i 1 PASS
done

CLIENTEXISTS=$(tail -n +2 $DF/easy-rsa/pki/index.txt | grep -c -E "/CN=$CLIENT\$")
if [[ $CLIENTEXISTS == '1' ]]; then
    echo ""
    echo "The specified client CN was already found in easy-rsa, please choose another name."
    exit
else
    cd $DF/easy-rsa/ || return
    case $PASS in
    1)
        EASYRSA_BATCH=1 EASYRSA_CERT_EXPIRE=3650 /usr/share/easy-rsa/easyrsa build-client-full "$CLIENT" nopass
        ;;
    2)
        echo "⚠️ You will be asked for the client password below ⚠️"
        EASYRSA_BATCH=1 EASYRSA_CERT_EXPIRE=3650 /usr/share/easy-rsa/easyrsa build-client-full "$CLIENT"
        ;;
    esac
    echo "Client $CLIENT added."
fi

# Determine if we use tls-auth or tls-crypt
if grep -qs "^tls-crypt" $DF/server.conf; then
    TLS_SIG="1"
elif grep -qs "^tls-auth" $DF/server.conf; then
    TLS_SIG="2"
fi

# Generates the custom client.ovpn
cp $DF/client-template.txt "$DF/client-certs/$CLIENT.ovpn"
{
    echo "<ca>"
    cat "$DF/easy-rsa/pki/ca.crt"
    echo "</ca>"

    echo "<cert>"
    awk '/BEGIN/,/END CERTIFICATE/' "$DF/easy-rsa/pki/issued/$CLIENT.crt"
    echo "</cert>"

    echo "<key>"
    cat "$DF/easy-rsa/pki/private/$CLIENT.key"
    echo "</key>"

    case $TLS_SIG in
    1)
        echo "<tls-crypt>"
        cat $DF/tls-crypt.key
        echo "</tls-crypt>"
        ;;
    2)
        echo "key-direction 1"
        echo "<tls-auth>"
        cat $DF/tls-auth.key
        echo "</tls-auth>"
        ;;
    esac
} >>"$DF/client-certs/$CLIENT.ovpn"
exit 0